### ISSUE TITLE
any plans to support swappable cells?

### ISSUE THREAD

**Issue by allanlaal** [offgridsystems/Documents#1]

**Comment by offgridsystems** [comment]
Yes the design of DKblock does allow you to swap cells when they wear out or go bad.
Also you can see the build process at https://dkblock922508958.wordpress.com/

![2016-07-06 15 01 42](https://user-images.githubusercontent.com/6006120/71794849-2ce7b900-2ff8-11ea-9a24-abd365d6e419.jpg)

**Comment by offgridsystems** [comment]
Just tested last night and found a cell swap takes about 5 minutes from start to finish, once you have the block isolated from the pack. You need a way to torque the screws to specification, I used the Dewalt DW920 screwdriver set to 4 in-lbs. Just make sure you get the cell polarity right, there is two ways to go, as the image above shows. The build (rebuild) guide is at https://github.com/offgridsystems/Documents/blob/master/DKblock%20assembly%20sheet%20OSHW%20V28OCT18.pdf.  

If that answers your question Allen, I'll close the issue. Does that adequately answer your question?
Tim

**Comment by allanlaal** [comment]
this type of replacement is satisfactory, but not quite the sitting on a rock in the middle of nowhere toolless (=multitool only) type of replacement

is it possible to add diodes for each cell, so that they wouldn't start welding themselves when the user mistakenly puts them in backwards?
 I've handled hundreds of cells and fried like 4 cheapo chinese chargers doing this, its inevitable just by statistics :)

**Comment by offgridsystems** [comment]
You can add diodes to each cell if you want, but no one building a battery will do that, losing 0.7Vx 4amp = 2.8watts at full load from each cell would be a tragedy of both heat buildup and energy loss, not to mention reduced voltage from the whole battery pack. Just don't put them in backwards, as you can see from my image above, it will look VERY obvious if you put them in backwards!
And can you do that sitting on a rock with a multitool, sure you can! They (like all high current battery connections) should be torqued properly, but if you break something way out in the boonies...hell yeah use whatever you have. And remember ... it's open source! You can change it to be whatever you want!
Tim

**Comment by offgridsystems** [comment]
Closing now, since question about swappable cells was answered. The DKblock is expressly designed for the ability to swap bad or worn cells easily. Ideas are always welcome on how to improve the design for this purpose.
Tim
