### ISSUE TITLE
Cell Holders?

### ISSUE THREAD

**Issue by BOOM-Mentoring** [offgridsystems/Documents#2]
Hello, your DK block shows cell-holders with pre-formed mounting holes. Where can i obtain these holders?

![image](https://user-images.githubusercontent.com/76221222/188212574-86f5c3ac-40aa-4db2-8cc0-b23b9b247553.png)

**Comment by thejobbitt** [comment]
Hey BOOM,

Here is a link to our [ebay store](https://www.ebay.com/usr/economu).

Let me know if you run into any other questions. I know the repros are messy.

_theJobbitt

**Comment by BOOM-Mentoring** [comment]
Thx!

________________________________
